import 'package:rescuenet_warehouse/pdf/packing_dangerous_good.dart';
import 'package:rescuenet_warehouse/pdf/packing_item.dart';
import 'package:rescuenet_warehouse/pdf/packing_list.dart';
import 'package:rescuenet_warehouse/pdf/summary_container.dart';
import 'package:rescuenet_warehouse/models/sequential_build.dart';

var summaryContainer = [
  SummaryContainer(
    containerNr: 1,
    name: "Office supplies",
    description: "Printer, tables, etc.",
    type: "Euro 60-40-32",
    value: 480,
    weight: 29.5,
    expirationDate: "May 5th, 2023",
    dangerousGoods: "Aerosol, non-flammable",
    coldChain: "",
    moduleDestination: "Office",
    sequentialBuild: SequentialBuild.firstBuild,
  ),
  SummaryContainer(
    containerNr: 2,
    name: "Cooler",
    description: "With cold packs and meds",
    type: "Cooler",
    value: 540,
    weight: 12,
    expirationDate: "Dec 12th, 2023",
    dangerousGoods: "",
    coldChain: "Yes",
    moduleDestination: "Storage",
    sequentialBuild: SequentialBuild.preBuild,
  ),
  SummaryContainer(
    containerNr: 3,
    name: "Fridge",
    description: "Electrical fridge",
    type: "Euro 60-40-32",
    value: 300,
    weight: 20,
    expirationDate: "",
    dangerousGoods: "",
    coldChain: "Yes",
    moduleDestination: "Storage",
    sequentialBuild: SequentialBuild.preBuild,
  ),
  SummaryContainer(
    containerNr: 4,
    name: "Tents",
    description: "Meeting tent",
    type: "Euro 60-40-32",
    value: 300,
    weight: 31,
    expirationDate: "",
    dangerousGoods: "",
    coldChain: "",
    moduleDestination: "Meeting area",
    sequentialBuild: SequentialBuild.laterBuild,
  ),
  SummaryContainer(
    containerNr: 5,
    name: "Sanitation",
    description: "Toilets, shower",
    type: "Euro 60-40-32",
    value: 300,
    weight: 25,
    expirationDate: "",
    dangerousGoods: "",
    coldChain: "",
    moduleDestination: "Meeting area",
    sequentialBuild: SequentialBuild.firstBuild,
  ),
  SummaryContainer(
    containerNr: 6,
    name: "Water filter 1",
    description: "Water filter for base camp",
    type: "Euro 60-40-32",
    value: 300,
    weight: 28.5,
    expirationDate: "",
    dangerousGoods: "",
    coldChain: "",
    moduleDestination: "Water treatment",
    sequentialBuild: SequentialBuild.laterBuild,
  ),
  SummaryContainer(
    containerNr: 7,
    name: "Water raw storage",
    description: "Storage 3800 liter raw water base camp",
    type: "Euro 60-40-32",
    value: 300,
    weight: 20,
    expirationDate: "",
    dangerousGoods: "",
    coldChain: "",
    moduleDestination: "Water treatment",
    sequentialBuild: SequentialBuild.laterBuild,
  ),
  SummaryContainer(
    containerNr: 8,
    name: "Power 1",
    description: "For fridge",
    type: "Euro 60-40-32",
    value: 300,
    weight: 30.5,
    expirationDate: "",
    dangerousGoods: "Flammable liquid Aerosol, non-flammable",
    coldChain: "Yes",
    moduleDestination: "Storage",
    sequentialBuild: SequentialBuild.preBuild,
  ),
  SummaryContainer(
    containerNr: 9,
    name: "Medical backpack 1",
    description: "",
    type: "Medical backpack",
    value: 300,
    weight: 18.5,
    expirationDate: "March 20th, 2024",
    dangerousGoods: "",
    coldChain: "",
    moduleDestination: "Storage",
    sequentialBuild: SequentialBuild.supplies,
  ),
];

var packingList = PackingList(
  containerNo: 1,
  containerType: "Euro L60xW40xH32",
  containerName: "Office supplies",
  containerDescription: "Printer, tables, etc,",
  totalWeight: 20.5,
  destination: "Office",
  sequentialBuild: SequentialBuild.firstBuild,
  expirationDate: DateTime(2023, 5),
  dangerousGoods: [packingDangerousGood],
  items: [
    packingItem1,
    packingItem2,
    packingItem3,
    ...[for (var i = 1; i <= 20; i++) packingItemX(i)],
  ],
);

var packingDangerousGood = PackingDangerousGood(
  dangerType: "Compressed gasses",
  iataId: "2.2 / 1950",
  properShippingName: "Aerosol, non-flammable",
  maxWeightPAX: 0.5,
  maxWeightCargo: 2.0,
  remarks: "Limited quantities LQ2",
  imagePath: "assets/images/DGcompressedgasses.png",
);

var packingItem1 = PackingItem(
  name: "Folding chair",
  description: "",
  amount: 13,
  piecePrice: 15,
  weightTotal: 12.2,
  expirationDate: DateTime(2023, 5, 5),
  dangerousGoods: "",
  remarks: "",
);

var packingItem2 = PackingItem(
  name: "Table",
  description: "",
  amount: 1,
  piecePrice: 75,
  weightTotal: 2.5,
  expirationDate: null,
  dangerousGoods: "",
  remarks: "",
);

var packingItem3 = PackingItem(
  name: "Fire Extinguisher",
  description: "FireEx 600 Airline safe aerogel cans",
  amount: 2,
  piecePrice: 100,
  weightTotal: 1.4,
  expirationDate: null,
  dangerousGoods: "2.2 / 1950",
  remarks: "Limited quantities LQ2",
);

PackingItem packingItemX(int n) => PackingItem(
  name: "Item $n",
  description: "",
  amount: 13,
  piecePrice: 15,
  weightTotal: 12.2,
  expirationDate: DateTime(2023, 5, 5),
  dangerousGoods: "",
  remarks: "",
);
