// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt7RWYyy-fsx0LUVq9RDp-L6NP_ippH4Q',
    appId: '1:954628027650:web:e693ffa92b453f1d93be1b',
    messagingSenderId: '954628027650',
    projectId: 'rescuenet-7733b',
    authDomain: 'rescuenet-7733b.firebaseapp.com',
    storageBucket: 'rescuenet-7733b.appspot.com',
    measurementId: 'G-6CRM3B77Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABfEUCB-0jyvtzAiJwW-Y07MgeAjfBcb0',
    appId: '1:954628027650:android:35baec43bcdfdc6793be1b',
    messagingSenderId: '954628027650',
    projectId: 'rescuenet-7733b',
    storageBucket: 'rescuenet-7733b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdgsk5M2VKuwyEk7s6lo_UtruttrPGRGU',
    appId: '1:954628027650:ios:bc6bf2aceb941ef893be1b',
    messagingSenderId: '954628027650',
    projectId: 'rescuenet-7733b',
    storageBucket: 'rescuenet-7733b.appspot.com',
    iosClientId: '954628027650-tjpi2enlscaadbd82hl7v3f1k7dsdid4.apps.googleusercontent.com',
    iosBundleId: 'net.rescuenet.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdgsk5M2VKuwyEk7s6lo_UtruttrPGRGU',
    appId: '1:954628027650:ios:5f242dc98009b23993be1b',
    messagingSenderId: '954628027650',
    projectId: 'rescuenet-7733b',
    storageBucket: 'rescuenet-7733b.appspot.com',
    iosClientId: '954628027650-oh45gom8k9bvmck5ph4o37rab7igppkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.rescuenetWarehouse',
  );
}
