// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// [FirebaseOptions] for RescueNet staging environment.
///
/// Example:
/// ```dart
/// import 'firebase_options_rescuenet_testing.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: RescuenetStagingFirebaseOptions.currentPlatform,
/// );
/// ```
class RescuenetStagingFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'RescuenetStagingFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'RescuenetStagingFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'RescuenetStagingFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8GzC11eX6c5idtjJGtlq_I-mN0uYdxIs',
    appId: '1:415629158289:web:5a52d6a8688710099f9c30',
    messagingSenderId: '415629158289',
    projectId: 'rescuenet-testing',
    authDomain: 'rescuenet-testing.firebaseapp.com',
    storageBucket: 'rescuenet-testing.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF3R-2ey1Yvp2yAYrh5BRBM2Da-KedV4M',
    appId: '1:415629158289:android:f02c0a78b58c15309f9c30',
    messagingSenderId: '415629158289',
    projectId: 'rescuenet-testing',
    storageBucket: 'rescuenet-testing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoFsSo0jFap0rYW5HhRgYGvJRLHrePTpY',
    appId: '1:415629158289:ios:9cb7353bb350bd229f9c30',
    messagingSenderId: '415629158289',
    projectId: 'rescuenet-testing',
    storageBucket: 'rescuenet-testing.firebasestorage.app',
    iosBundleId: 'net.rescuenet.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoFsSo0jFap0rYW5HhRgYGvJRLHrePTpY',
    appId: '1:415629158289:ios:9c4cb5d844914cf29f9c30',
    messagingSenderId: '415629158289',
    projectId: 'rescuenet-testing',
    storageBucket: 'rescuenet-testing.firebasestorage.app',
    iosBundleId: 'com.example.rescuenetWarehouse',
  );
}
