// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_humedica_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: HumedicaFirebaseOptions.currentPlatform,
/// );
/// ```
class HumedicaFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCBOvgbvX5LXamJgGhrlCg1GLVq3kT1Us',
    appId: '1:106038107645:web:69b6f4799f52152af18d94',
    messagingSenderId: '106038107645',
    projectId: 'humedica-e767c',
    authDomain: 'humedica-e767c.firebaseapp.com',
    storageBucket: 'humedica-e767c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQAhabmYjdHobKhGy-Q02s7zXzwrLq1VQ',
    appId: '1:106038107645:android:8c91ef6bc12a924ff18d94',
    messagingSenderId: '106038107645',
    projectId: 'humedica-e767c',
    storageBucket: 'humedica-e767c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTMsME6tlkQzYNESU5QuFYNPTB7qekF9Q',
    appId: '1:106038107645:ios:fb21787df00e4a79f18d94',
    messagingSenderId: '106038107645',
    projectId: 'humedica-e767c',
    storageBucket: 'humedica-e767c.firebasestorage.app',
    iosBundleId: 'net.rescuenet.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTMsME6tlkQzYNESU5QuFYNPTB7qekF9Q',
    appId: '1:106038107645:ios:d6181c159172ba23f18d94',
    messagingSenderId: '106038107645',
    projectId: 'humedica-e767c',
    storageBucket: 'humedica-e767c.firebasestorage.app',
    iosBundleId: 'com.example.rescuenetWarehouse',
  );
}
